version: '3.8'
services:
  app:
    build: ./unified-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: npm run start:prod
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/yourdbname

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=yourdbname

volumes:
  mongo-data:
